language: cpp
os: osx
osx_image: xcode8.3
compiler:
- clang

cache:
  directories:
  - $HOME/build/CARTAvis/CARTAvis-external/ThirdParty
  # - $HOME/Library/Caches/Homebrew

install: true
script:
  - echo "stage1- thirdparty"
  - if [ -f "$HOME/build/CARTAvis/CARTAvis-external/ThirdParty" ]; then echo "third party exist";ls $HOME/build/CARTAvis/CARTAvis-external/ThirdParty;else echo "no thridparty there"; fi
  - cd ..
  - mv carta CARTAvis
  - sudo -E ./CARTAvis/carta/scripts/ci_mac_thirdparty.sh
  - rm -rf $HOME/build/CARTAvis/CARTAvis-external/ThirdParty/qooxdoo-3.5.1-sdk
  - echo "test third party"
  - cd $HOME/build/CARTAvis/CARTAvis-external/ThirdParty
  - ls -l
  - echo "aaa" > ${TRAVIS_JOB_NUMBER}.txt
  - echo "build folder:"
  - ls -al $HOME/build
  - echo "CARTAvis folder:"
  - ls -al $HOME/build/CARTAvis
  - echo "CARTAvis/CARTAvis-external:"
  - ls -al $HOME/build/CARTAvis/CARTAvis-external
  - echo "git folder:"
  - ls -al $HOME/build/CARTAvis/CARTAvis
before_cache:
  - rm -rf $HOME/build/CARTAvis/CARTAvis-external/ThirdParty/ast-8.4.0-src
  - rm -rf $HOME/build/CARTAvis/CARTAvis-external/ThirdParty/ast-8.4.0.tar.gz
  - rm -rf $HOME/build/CARTAvis/CARTAvis-external/ThirdParty/qwt-6.1.2-src
  - rm -rf $HOME/build/CARTAvis/CARTAvis-external/ThirdParty/qwt-6.1.2.tar.bz2

# before_install:
  # - echo "in before_install"
  # - echo "list cache Third party folder"
  # - if [ -f "$HOME/build/CARTAvis/CARTAvis-external/ThirdParty" ]; then ls -al $HOME/build/CARTAvis/CARTAvis-external/ThirdParty; else echo "no Third party there";fi
  # - cd ..
  # - mv carta CARTAvis
  # - git clone https://github.com/grimmer0125/testgdrive.git
  # - npm install
  # - chmod 755 ./CARTAvis/carta/scripts/ci_mac2.sh
  # - sudo -E ./CARTAvis/carta/scripts/ci_mac2.sh

# install:
#   - echo "in install" # can do something like npm install
#   - echo `pwd`

# script:
  # - echo "in script step"
  # - echo "some logs:"
  # - echo "in script:"
  # - echo `pwd`
  # - echo $TRAVIS_BUILD_DIR
  # - which wget
  # - node --version
  # - echo "ls"
  # - ls -l
  # - brew list
  # - ls /usr/local/include/c++
  # - which python
  # - python --version, 2.7.13, homebrew

  #$HOME/build/CARTAvis
  # upload final dmg
  # ls -al $CARTABUILDHOME/Carta-${OS_X_VERSION}-${cartaver}.dmg
  # Carta-10.12-0.9.0.dmg

jobs:
  include:
    - stage: buildcasa
      install: true
      script:
        - echo "stage2- buildcasa"
        - echo "2-1"
        - ls -l $HOME/build/CARTAvis/CARTAvis-external/
        - echo "2-2"
        - ls -l $HOME/build/CARTAvis/CARTAvis-external/ThirdParty
        - if [ -f "$HOME/build/CARTAvis/CARTAvis-external/ThirdParty" ]; then echo "third party exist";ls $HOME/build/CARTAvis/CARTAvis-external/ThirdParty;else echo "no thridparty there"; fi
        - cd ..
        - mv carta CARTAvis
    #     - sudo -E ./CARTAvis/carta/scripts/ci_mac_buildcasa.sh
    #   before_cache:
    #     - rm -rf $HOME/build/CARTAvis/CARTAvis-external/ThirdParty/libsakura
    #     - mv $HOME/build/CARTAvis/CARTAvis-external/ThirdParty/casa/trunk/darwin $HOME/build/CARTAvis/CARTAvis-external/ThirdParty/
    #     - rm -rf $HOME/build/CARTAvis/CARTAvis-external/ThirdParty/casa
    #     - mkdir -p $HOME/build/CARTAvis/CARTAvis-external/ThirdParty/casa/trunk
    #     - mv $HOME/build/CARTAvis/CARTAvis-external/ThirdParty/darwin $HOME/build/CARTAvis/CARTAvis-external/ThirdParty/casa/trunk/
    # - stage: buildcarta
    #   install: true
    #   script:
    #     - echo "stage3, buildcarta, in script, current folder:"
    #     - if [ -f "$HOME/build/CARTAvis/CARTAvis-external/ThirdParty" ]; then echo "third party exist";ls $HOME/build/CARTAvis/CARTAvis-external/ThirdParty;else echo "no thridparty there"; fi
    #     - unzip $HOME/build/CARTAvis/CARTAvis-external/ThirdParty/qooxdoo-3.5.1-sdk -d $HOME/build/CARTAvis/CARTAvis-external/ThirdParty -d > /dev/null
    #     - sudo easy_install cython
    #     - sudo easy_install pip
    #     - pip install matplotlib --user -U
    #     - cd ..
    #     - mv carta CARTAvis
    #     - chmod 755 ./CARTAvis/carta/scripts/ci_mac.sh
    #     - sudo -E ./CARTAvis/carta/scripts/ci_mac_buildcasa.sh
    #     - git clone https://github.com/grimmer0125/testgdrive.git
    #     - npm install
    #     - if [ -f "$HOME/build/CARTAvis/CARTAvis/build/Carta-10.12-0.9.0.dmg" ]; then echo "dmg exist"; mv $HOME/build/CARTAvis/CARTAvis/build/Carta-10.12-0.9.0.dmg ./testgdrive/;cd testgdrive;npm start;else echo "no dmg there"; fi
    #     - rm -rf $HOME/build/CARTAvis/CARTAvis-external/ThirdParty/qooxdoo-3.5.1-sdk
    #   before_cache:
    #     # - rm -rf $HOME/build/CARTAvis/CARTAvis-external/ThirdParty/libsakura
    #     # - rm -rf $HOME/build/CARTAvis/CARTAvis-external/ThirdParty/gsl*
    #     # - rm -rf $HOME/build/CARTAvis/CARTAvis-external/ThirdParty/qooxdoo-3.5.1-sdk
    #     - rm -rf $HOME/build/CARTAvis/CARTAvis-external/ThirdParty/qtwebkit-tp4-qt57-darwin*
    #     # - cd $HOME/build/CARTAvis/CARTAvis-external/ThirdParty
    #     # - echo `pwd`
    #     # - ls
