language: cpp
os: osx
osx_image: xcode8.3
compiler:
- clang

cache:
  directories:
  - $HOME/build/CARTAvis/CARTAvis-external/ThirdParty
before_cache:
  - rm -rf $HOME/build/CARTAvis/CARTAvis-external/ThirdParty/libsakura
  - rm -rf $HOME/build/CARTAvis/CARTAvis-external/ThirdParty/gsl*
  - rm -rf $HOME/build/CARTAvis/CARTAvis-external/ThirdParty/qooxdoo-3.5.1-sdk
  - rm -rf $HOME/build/CARTAvis/CARTAvis-external/ThirdParty/ast-8.4.0-src
  - rm -rf $HOME/build/CARTAvis/CARTAvis-external/ThirdParty/ast-8.4.0.tar.gz
  - rm -rf $HOME/build/CARTAvis/CARTAvis-external/ThirdParty/qwt-6.1.2-src
  - rm -rf $HOME/build/CARTAvis/CARTAvis-external/ThirdParty/qwt-6.1.2.tar.bz2
  - mv $HOME/build/CARTAvis/CARTAvis-external/ThirdParty/casa/trunk/darwin $HOME/build/CARTAvis/CARTAvis-external/ThirdParty/
  - rm -rf $HOME/build/CARTAvis/CARTAvis-external/ThirdParty/casa
  - mkdir -p $HOME/build/CARTAvis/CARTAvis-external/ThirdParty/casa/trunk
  - mv $HOME/build/CARTAvis/CARTAvis-external/ThirdParty/darwin $HOME/build/CARTAvis/CARTAvis-external/ThirdParty/casa/trunk/
  - rm -rf $HOME/build/CARTAvis/CARTAvis-external/ThirdParty/qtwebkit-tp4-qt57-darwin*

before_install:
  - echo "in before_install"
  - export testtest=123
  - echo $testtest
  - echo "afte testtest"
  - echo "list cache Third party folder"
  - if [ -f "$HOME/build/CARTAvis/CARTAvis-external/ThirdParty" ]; then ls -al $HOME/build/CARTAvis/CARTAvis-external/ThirdParty; else echo "no Third party there";fi
  - cd ..
  - mv carta CARTAvis
  - git clone https://github.com/grimmer0125/testgdrive.git
  - npm install
  - chmod 755 ./CARTAvis/carta/scripts/ci_mac2.sh
  - export TRAVIS
  - sudo -E ./CARTAvis/carta/scripts/ci_mac2.sh

install:
  - echo "in install" # can do something like npm install
  - echo `pwd`

script:
  # - echo "in script step"
  # - echo "some logs:"
  # - echo "in script:"
  # - echo `pwd`
  # - echo $TRAVIS_BUILD_DIR
  # - which wget
  # - node --version
  # - echo "ls"
  # - ls -l
  # - brew list
  # - ls /usr/local/include/c++
  # - which python
  # - python --version, 2.7.13, homebrew
  - echo "in script, current folder:"
  - echo `pwd`
  - echo "start build"
  - cd $HOME/build/CARTAvis
  # - mv carta CARTAvis
  - chmod 755 ./CARTAvis/carta/scripts/ci_mac.sh
  - export TRAVIS
  - sudo -E ./CARTAvis/carta/scripts/ci_mac.sh
  # - git clone https://github.com/grimmer0125/testgdrive.git
  - if [ -f "$HOME/build/CARTAvis/CARTAvis/build/Carta-10.12-0.9.0.dmg" ]; then echo "dmg exist"; mv $HOME/build/CARTAvis/CARTAvis/build/Carta-10.12-0.9.0.dmg ./testgdrive/;cd testgdrive;npm start;else echo "no dmg there"; fi

  #$HOME/build/CARTAvis
  # upload final dmg
  # ls -al $CARTABUILDHOME/Carta-${OS_X_VERSION}-${cartaver}.dmg
  # Carta-10.12-0.9.0.dmg
