# language seems to be the minimized setting
# language: ruby
# rvm:
#  - 2.2
#  - jruby
#  - rbx-2

# language seems to be ruby,
# https://github.com/travis-ci/travis-ci/issues/4895
os: osx
osx_image: xcode8.3

cache:
  directories:
  - $HOME/build/CARTAvis/CARTAvis-external/ThirdParty

before_cache:
  - echo "in before cache"

# compiler:
# - clang

# In a before_install step, you can install additional dependencies required by your project such as Ubuntu packages or custom services.
before_install:
# - brew update

# The default dependency installation commands depend on the project language. For instance, Java builds either use Maven or Gradle, depending on which build file is present in the repository. Ruby projects use Bundler when a Gemfile is present in the repository.
#
# You can specify your own script to run to install whatever dependencies your project requires in .travis.yml:
install:
  - echo "in install:"
  - echo `pwd`

# You can skip the installation step entirely by adding the following to your .travis.yml:
# install: true

# before_script:

#The default build command depends on the project language
script: # build
  - echo "in script  !!"
  - if [ -f "$HOME/build/CARTAvis/CARTAvis-external/ThirdParty" ]; then echo "Thiry exist, no create";  else mkdir -p $HOME/build/CARTAvis/CARTAvis-external/ThirdParty; fi
  - cd $HOME/build/CARTAvis/CARTAvis-external/ThirdParty
  - echo `pwd`
  - ls
  - echo "try to write data to cache"
  - echo ${TRAVIS_JOB_ID}
  - echo ${TRAVIS_JOB_NUMBER}
  - echo "aaa" > ${TRAVIS_JOB_NUMBER}.txt
  # - if [ -f "$HOME/build/CARTAvis/CARTAvis-external/ThirdParty" ]; then echo "ls 3party";ls $HOME/build/CARTAvis/CARTAvis-external/ThirdParty;  else echo "no Third party there";fi
  # - echo "try to write data to cache"
  # - ls
  # - ls aaa
  # - gcc --version
  # - ls /usr/local/include/c++
  # #- which gfortran
  # - echo $TRAVIS
  # - rm '/usr/local/include/c++'
  # - brew install gcc
  # - ls /usr/local/bin/gfortran
  # - afplay /System/Library/Sounds/Funk.aiff
  # - echo "in script:"
  # - echo `pwd`
  # - echo $TRAVIS_BUILD_DIR
  # - which wget
  # - node --version
  # - echo "ls"
  # - ls
  # - brew list
  # - ls /usr/local/bin/gfortran # ls /usr/local/bin/gfortran" exited with 1
  # - echo "start build"
  # - cd .. # should become /Users/travis/build/CARTAvis/
  # - mv carta CARTAvis
  # - sudo sh ./CARTAvis/carta/scripts/ci_mac2.sh

# /Users/travis/build/CARTAvis/carta
# /Users/travis/build/CARTAvis/CARTAvis
# /Users/travis/build/CARTAvis/CARTAvis-external
# cmake 3.6.2 ?3.8.1
# autoconf 2.69
# automake 1.15
