language: cpp
os: osx
osx_image: xcode8.3
compiler:
- clang

cache:
  directories:
  - $HOME/build/CARTAvis/CARTAvis-external/ThirdParty
before_cache:
  - rm -rf $HOME/build/CARTAvis/CARTAvis-external/ThirdParty/libsakura
  - rm -rf $HOME/build/CARTAvis/CARTAvis-external/ThirdParty/gsl*
  - rm -rf $HOME/build/CARTAvis/CARTAvis-external/ThirdParty/qooxdoo-3.5.1-sdk
  - rm -rf $HOME/build/CARTAvis/CARTAvis-external/ThirdParty/ast-8.4.0-src
  - rm -rf $HOME/build/CARTAvis/CARTAvis-external/ThirdParty/ast-8.4.0.tar.gz
  - rm -rf $HOME/build/CARTAvis/CARTAvis-external/ThirdParty/qwt-6.1.2-src
  - rm -rf $HOME/build/CARTAvis/CARTAvis-external/ThirdParty/qwt-6.1.2.tar.bz2
  - mv $HOME/build/CARTAvis/CARTAvis-external/ThirdParty/casa/trunk/darwin $HOME/build/CARTAvis/CARTAvis-external/ThirdParty/
  - rm -rf $HOME/build/CARTAvis/CARTAvis-external/ThirdParty/casa
  - mkdir -p $HOME/build/CARTAvis/CARTAvis-external/ThirdParty/casa/trunk
  - mv $HOME/build/CARTAvis/CARTAvis-external/ThirdParty/darwin $HOME/build/CARTAvis/CARTAvis-external/ThirdParty/casa/trunk/
  - rm -rf $HOME/build/CARTAvis/CARTAvis-external/ThirdParty/qtwebkit-tp4-qt57-darwin*

install:
  - echo "in install"

script:
  - echo "in script step"
  - echo "some logs:"
  - echo "in script:"
  - echo `pwd`
  - echo $TRAVIS_BUILD_DIR
  - which wget
  - node --version
  - echo "ls"
  - ls -l
  - brew list
  - ls /usr/local/include/c++
  - which python
  - python --version
  - echo "list cache Third party folder"
  - ls -al $HOME/build/CARTAvis/CARTAvis-external/ThirdParty
  - echo "start build"
  - cd ..
  - mv carta CARTAvis
  - sudo sh -E ./CARTAvis/carta/scripts/ci_mac2.sh
